//Index for all Icons to reduce import size
export { default as AngryIcon } from './AngryIcon'
export { default as HappyIcon } from './HappyIcon'
export { default as SadIcon } from './SadIcon'
export { default as NeutralIcon } from './NeutralIcon'
export { default as SurpriseIcon } from './SurpriseIcon'
export { default as FearIcon } from './FearIcon'
export { default as SickIcon } from './SickIcon'
export { default as ContemptIcon } from './ContemptIcon'
export { default as RobotIcon} from './RobotIcon'
export { default as Clapperboard } from './Clapperboard'
export { default as Monitorplay } from './Monitorplay'
export { default as MuteIcon } from './MuteIcon'
export { default as PauseButton } from './PauseButton'
export { default as PlayButton } from './PlayButton'
export { default as Popcorn } from './Popcorn'
export { default as VolumeIcon } from './VolumeIcon'
export { default as DramaIcon } from './DramaIcon'